- name: Install MySQL
  apt:
      name: mysql-server
      state: present
  register: mysql_installed
- name: Install python3-mysqldb
  apt:
    name: python3-mysqldb
    state: present
- name: Creating Mysql user
  mysql_user:
       name: "{{login_user}}"
       password: "{{login_password}}"
       priv: '*.*:ALL,GRANT'
       host: 'localhost'
  when: mysql_installed.changed
- name: Creating Database
  mysql_db:
    login_user: "{{login_user}}"
    login_password: "{{login_password}}"
    db: "{{db_name}}" 
    state: present
  when: mysql_installed.changed
