- name: installing common software
  apt:
   name: software-properties-common
   state: latest

- name: Add PHP 7 PPA repository
  apt_repository:
    repo: 'ppa:ondrej/php'
  register: php_installed

- name: Install PHP packages
  apt: name={{ item }} state=latest
  loop: [ 'php7.3-common', 'php7.3-mysql', 'php7.3-fpm','php7.3-xml', 'php7.3-curl', 'php7.3-gd', 'php7.3-imagick']

- name: enabling php service
  command: systemctl enable php7.3-fpm
  when: php_installed.changed

- name: changing max_execution_time
  replace:
    path: /etc/php/7.3/fpm/php.ini
    regexp: 'max_execution_time = 30'
    replace: 'max_execution_time=300'
    owner: root
    group: root
    mode: 0644
- name: Enabling opne shot Tag in php.ini
  replace:
    path: /etc/php/7.3/fpm/php.ini
    regexp: '; short_open_tag'
    replace: 'short_open_tag = off'
    owner: root
    group: root
    mode: 0644
